---
title: "Oferta Educativa y Laboral - exploración inicial de datos"
format: html
---


```{r}
#| echo: FALSE
#| include: FALSE  # Prevents the entire chunk from appearing in the output
library(skimr)
```


```{r}
#| echo: FALSE   # Prevents code from being shown
#| message: FALSE # Suppresses messages
#| warning: FALSE # Suppresses warnings
#| results: 'hide' # Hides the output of the code
#| include: FALSE  # Prevents the entire chunk from appearing in the output


# Load rdata file with directory locations

# Load renv properly and set working directory to the project root:
project_root <- "~/Documents/work/comp_med_medicina_datos/projects/int_op/oferta_educativa_laboral/"

# TO DO: needs a yaml with a results dir, this saves in scripts dir
processed_dir <- "data/data_UP/access_SIAP_18092024/processed/"
# infile <- "2b_subset_enfermeras_2_dups_col_types_Qna_17_Plantilla_2024.rdata.gzip"
# infile <- "2b_subset_meds_2_dups_col_types_Qna_17_Plantilla_2024.rdata.gzip"   
infile <- '2_clean_dups_col_types_Qna_17_Bienestar_2024.rdata.gzip'
# infile <- '2_clean_dups_col_types_Qna_17_Plantilla_2024.rdata.gzip'

infile_prefix <- strsplit(infile, "\\.")[[1]][1]
load(file.path(paste0(project_root, processed_dir, infile)))
```



```{r}
#| echo: FALSE

# Generate the skim summary
skim_summary <- skim(data_f)
skim_summary
```


```{r}
#| echo: FALSE
#| include: FALSE  # Prevents the entire chunk from appearing in the output

# TO DO: This does not work
# Clean up files as qmd saves them in the scripts folder:
# move_to <- file.path(paste0(results_dir, "/",
#                      infile_prefix,
#                      "_3b_skim_summary.html"
#                      ))
move_to <- file.path(paste0(results_dir, "/",
                     "3b_skim_summary.html"
                     ))
if (file.exists(move_to)) {
    file.remove(move_to)
    file.rename("3b_skim_summary.html", move_to)
    } else {
        file.rename("3b_skim_summary.html", move_to)
    }

if (dir.exists("3b_skim_summary_files")) {
  unlink("3b_skim_summary_files", recursive = TRUE)
}
```
