---
title: "Oferta Educativa y Laboral - exploración inicial de datos"
format: html
---


```{r}
#| echo: FALSE
library(skimr)
```


```{r}
#| echo: FALSE   # Prevents code from being shown
#| message: FALSE # Suppresses messages
#| warning: FALSE # Suppresses warnings
#| results: 'hide' # Hides the output of the code
#| include: FALSE  # Prevents the entire chunk from appearing in the output


# Load rdata file with directory locations

# Load renv properly and set working directory to the project root:
setwd(here::here())
getwd()
# Load the .rdata.gzip file:
# TO DO: needs a yaml with a results dir, this saves in scripts dir
processed_dir <- "data/data_UP/access_SIAP_18092024/processed/"
infile <- "2b_subset_enfermeras_2_dups_col_types_Qna_17_Plantilla_2024.rdata.gzip"
# infile <- "2b_subset_meds_2_dups_col_types_Qna_17_Plantilla_2024.rdata.gzip"   
# infile <- "2_dups_col_types_Qna_17_Plantilla_2024.rdata.gzip"
load(paste0(processed_dir, infile))
```



```{r}
#| echo: FALSE

# Generate the skim summary
skim_summary <- skim(data_f)
skim_summary
```
